version: '3'

services:
  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"  # KRaft modunu etkinleştir
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9091"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093"  # Her iki broker için aynı port kullanılmalı
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Tek broker için bu değer 1 olmalı

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"  # KRaft modunu etkinleştir
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093"  # Her iki broker için aynı port kullanılmalı
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Tek broker için bu değer 1 olmalı

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092"  # Kafka broker'larının adresleri
      CONTROL_CENTER_REPLICATION_FACTOR: 1  # Tek broker için bu değer 1 olmalı
